[core]
data_dir = ~/.local/share/mopidy
max_tracklist_length = 10000
restore_state = false

[logging]
verbosity = 0
format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
color = true

[audio]
mixer = software
mixer_volume =
output = pulsesink
visualizer =

[file]
enabled = false

[m3u]
enabled = true
playlists_dir = %%JUKEBOX_PLAYLISTS_PATH%%

[local]
enabled = true
media_dir = %%JUKEBOX_AUDIOFOLDERS_PATH%%
scan_timeout = 1000
scan_flush_threshold = 100
excluded_file_extensions =
  .conf
  .jpg
  .jpeg
  .png
  .txt
  .yaml

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600
password =
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist =
  listall
  listallinfo
default_playlist_scheme = m3u

[http]
enabled = true
hostname = 127.0.0.1
port = 6680
zeroconf = Mopidy HTTP server on $hostname
allowed_origins =

[iris]
enabled = true
country = DE
locale = de_DE
verify_certificates = true

[spotify]
enabled = true
client_id = %%SPOTIFY_CLIENT_ID%%
client_secret = %%SPOTIFY_CLIENT_SECRET%%
bitrate = 160
volume_normalization = true
private_session = false
timeout = 10
allow_cache = true
allow_network = true
allow_playlists = true
search_album_count = 20
search_artist_count = 10
search_track_count = 50
